### ISSUE TITLE
React-Native 0.60+

### ISSUE THREAD

**Issue by MokumJ** [Notificare/notificare-push-lib-react-native#4]
Anybody got this working on react-native 0.60 or more?

Currently trying to make it work but keep on bumping into the error:
`'NotificarePushLib.h' file not found`
 
When I link the library: libNotificarePushLibReactNative.a  with binary,

I get the error: `'React/RCTBridgeModule.h' file not found.`

Can't seem to get around it. Anyone a solution?

**Comment by jjonthemix** [comment]
Hi MokumJ,

Did you follow the instructions located here:

https://docs.notifica.re/sdk/v2/react-native/ios/implementation/

You need to use our React Native module 2.1.0 in order to have support for 0.60 or higher. 

Additionally, please use support@notifica.re for any further question you might have.

Regards,
